version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./docker/data/db:/var/lib/postgresql/data
      - ./docker/initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secretpgpassword}
    ports:
      - '5432:5432'
  graphql-engine:
    image: hasura/graphql-engine:v2.2.0
    depends_on:
      - postgres
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD:-secretpgpassword}@postgres:5432/postgres
      HASURA_GRAPHQL_JWT_SECRET: ${HASURA_GRAPHQL_JWT_SECRET}
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: public
      HASURA_GRAPHQL_LOG_LEVEL: debug
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
    ports:
      - '8080:8080'
  hasura-auth:
    image: nhost/hasura-auth:latest
    depends_on:
      - postgres
      - graphql-engine
    env_file:
      - .env
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD:-secretpgpassword}@postgres:5432/postgres
      HASURA_GRAPHQL_GRAPHQL_URL: http://graphql-engine:8080/v1/graphql
      AUTH_SMTP_HOST: mailhog
      AUTH_SMTP_PORT: 1025
    ports:
      - '4000:4000'
    volumes:
      - ./email-templates:/app/email-templates
  mailhog:
    image: mailhog/mailhog
    environment:
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_PASS: ${AUTH_SMTP_PASS}
      SMTP_USER: ${AUTH_SMTP_USER}
      SMTP_SECURE: '${AUTH_SMTP_SECURE}'
      SMTP_SENDER: ${AUTH_SMTP_SENDER}
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    volumes:
      - ./docker/data/mailhog:/maildir
