version: '3.6'
services:
  hasura-auth:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: '.env.test'
    depends_on:
      - 'mailhog'
    environment:
      NODE_ENV: test
      JWT_ALGORITHM: HS256
      JWT_KEY: '${JWT_KEY}'
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_SECURE: 'false'
    ports:
      - '9229:9229'
    volumes:
      - .:/app
      - /app/node_modules
  graphql-engine:
    ports:
      - '8080:8080'
    environment:
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "HS256", "key": "${JWT_KEY}"}'
      HASURA_GRAPHQL_ENABLED_CONSOLE: 'true'
  mailhog:
    image: mailhog/mailhog
