version: '3.6'
services:
  hasura-auth:
    command: npm run dev-command
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: '.env.development'
    depends_on:
      - 'mailhog'
    environment:
      NODE_ENV: development
      JWT_ALGORITHM: HS256
      JWT_KEY: '${JWT_KEY}'
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_SECURE: 'false'
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '9229:9229'
  graphql-engine:
    ports:
      - '8080:8080'
    environment:
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "HS256", "key": "${JWT_KEY}"}'
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
