#name: Deploy
#
#on:
#  push:
#    branches: [main]
#
#  workflow_dispatch:
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@master
#      - uses: actions/setup-node@master
#        with:
#          node-version: 14
#      - run: npm install -g yarn
#      - run: yarn install --frozen-lockfile
#      - run: yarn build
#
#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@master
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: eu-west-1
#      - run: aws s3 sync ./out s3://helios-next-chakra-ui-starter-kit
