metadata_directory: metadata
services:
  hasura:
    environment:
      hasura_graphql_enable_remote_schema_permissions: false
  minio:
    environment:
      minio_root_password: minioaccesskey123123
      minio_root_user: minioaccesskey123123
  postgres:
    environment:
      postgres_password: postgres
      postgres_user: postgres
auth:
  access_control:
    email:
      allowed_email_domains: ""
      allowed_emails: ""
      blocked_email_domains: ""
      blocked_emails: ""
    url:
      allowed_redirect_urls: ""
  anonymous_users_enabled: false
  client_url: http://localhost:3000
  disable_new_users: false
  email:
    enabled: false
    passwordless:
      enabled: false
    signin_email_verified_required: true
    template_fetch_url: ""
  gravatar:
    default: ""
    enabled: true
    rating: ""
  locale:
    allowed: en
    default: en
  password:
    hibp_enabled: false
    min_length: 3
  provider:
    apple:
      client_id: ""
      enabled: false
      key_id: ""
      private_key: ""
      scope: name,email
      team_id: ""
    bitbucket:
      client_id: ""
      client_secret: ""
      enabled: false
    facebook:
      client_id: ""
      client_secret: ""
      enabled: false
      scope: email,photos,displayName
    github:
      client_id: ""
      client_secret: ""
      enabled: false
      scope: user:email
      token_url: ""
      user_profile_url: ""
    gitlab:
      base_url: ""
      client_id: ""
      client_secret: ""
      enabled: false
      scope: read_user
    google:
      client_id: ""
      client_secret: ""
      enabled: false
      scope: email,profile
    linkedin:
      client_id: ""
      client_secret: ""
      enabled: false
      scope: r_emailaddress,r_liteprofile
    spotify:
      client_id: ""
      client_secret: ""
      enabled: false
      scope: user-read-email,user-read-private
    strava:
      client_id: ""
      client_secret: ""
      enabled: false
    twilio:
      account_sid: ""
      auth_token: ""
      enabled: false
      messaging_service_id: ""
    twitter:
      consumer_key: ""
      consumer_secret: ""
      enabled: false
    windows_live:
      client_id: ""
      client_secret: ""
      enabled: false
      scope: wl.basic,wl.emails,wl.contacts_emails
  sms:
    enabled: false
    passwordless:
      enabled: false
    provider:
      twilio:
        account_sid: ""
        auth_token: ""
        from: ""
        messaging_service_id: ""
  smtp:
    host: mailhog
    method: ""
    pass: password
    port: 1025
    secure: false
    sender: hasura-auth@example.com
    user: user
  token:
    access:
      expires_in: 900
    refresh:
      expires_in: 43200
  user:
    allowed_roles: user,me
    default_allowed_roles: user,me
    default_role: user
    mfa:
      enabled: false
      issuer: nhost
storage:
  force_download_for_content_types: text/html,application/javascript
version: 3
