---
name: "codegen: check changelog"
on:
  pull_request:
    paths:
      - 'flake.nix'
      - 'flake.lock'
      - 'nix/**'
      - 'build/**'
      - "tools/codegen/**"

jobs:
  check-changelog:
    uses: ./.github/workflows/wf_check_changelog.yaml
    with:
      PROJECT_PATH: tools/codegen
