---
name: Release
on:
  release:
    types: [published]

jobs:
  tests:
    uses: ./.github/workflows/wf_check.yaml
    with:
      NAME: hasura-auth

  build_artifacts:
    uses: ./.github/workflows/wf_build_artifacts.yaml
    with:
      NAME: hasura-auth
      VERSION: ${{ github.ref_name }}
      DOCKER: true

  push_docker_image:
    uses: ./.github/workflows/wf_docker_push_image.yaml
    needs:
      - tests  # we depend of tests here to paralleliza tests and build
      - build_artifacts
    with:
      NAME: hasura-auth
      VERSION: ${{ github.ref_name }}
      AWS_REGION: eu-central-1
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_PRODUCTION_CORE_ACCOUNT_ID }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
