---
name: Run tests and linters

on:
  workflow_call:
    secrets:
      CACHIX_AUTH_TOKEN:
        required: true


jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: nixbuild/nix-quick-install-action@v28
      with:
        nix_version: 2.16.2
        nix_conf: |
          experimental-features = nix-command flakes
          sandbox = false

    - name: Cache nix store
      uses: actions/cache@v4
      with:
        path: /nix
        key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix') }}

    - uses: cachix/cachix-action@v14
      with:
        name: hasura-storage
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

    - name: "Start containters for integration tests"
      run: make dev-env-up

    - name: "Run checks"
      run: make check
