---
on:
  workflow_call:
    inputs:
      NAME:
        type: string
        required: true
      VERSION:
        type: string
        required: true
      AWS_REGION:
        type: string
        required: true

    secrets:
      AWS_ACCOUNT_ID:
        required: true
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  push-to-ecr:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions:
      id-token: write
      contents: write

    steps:
      - name: "Check out repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: "Compute common env vars"
        id: vars
        run: |
          echo "VERSION=$(make get-version VER=${{ inputs.VERSION }})" >> $GITHUB_OUTPUT

      - name: "Configure aws"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-nhost-${{ github.event.repository.name }}
          aws-region: eu-central-1

      - name: "Login to Amazon ECR"
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'

      - name: "Get artifacts"
        uses: actions/download-artifact@v4
        with:
          path: ~/artifacts

      - name: "Push docker image to EKS"
        run: |
          export NAME=${{ inputs.NAME }}
          export VERSION=${{ steps.vars.outputs.VERSION }}
          export CONTAINER_REGISTRY=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.AWS_REGION }}.amazonaws.com
          export CONTAINER_NAME=$CONTAINER_REGISTRY/$NAME

          for ARCH in "x86_64" "aarch64"; do
            docker load < ~/artifacts/${{ inputs.NAME }}-docker-image-$ARCH-$VERSION/result
            docker tag $NAME:$VERSION $CONTAINER_NAME:$VERSION-$ARCH
            docker push $CONTAINER_NAME:$VERSION-$ARCH
          done

          docker manifest create \
            $CONTAINER_NAME:$VERSION \
            --amend $CONTAINER_NAME:$VERSION-x86_64 \
            --amend $CONTAINER_NAME:$VERSION-aarch64

          docker manifest push $CONTAINER_NAME:$VERSION

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Push docker image to docker hub"
        run: |
          export NAME=${{ inputs.NAME }}
          export VERSION=${{ steps.vars.outputs.VERSION }}
          export CONTAINER_REGISTRY=nhost
          export CONTAINER_NAME=$CONTAINER_REGISTRY/$NAME

          for ARCH in "x86_64" "aarch64"; do
            docker load < ~/artifacts/${{ inputs.NAME }}-docker-image-$ARCH-$VERSION/result
            docker tag $NAME:$VERSION $CONTAINER_NAME:$VERSION-$ARCH
            docker push $CONTAINER_NAME:$VERSION-$ARCH
          done

          docker manifest create \
            $CONTAINER_NAME:$VERSION \
            $OPTS

          docker manifest push $CONTAINER_NAME:$VERSION
